[CmdletBinding()]
param([string]$InstallPath=(Join-Path $env:ProgramFiles 'Evora'))
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSCommandPath
$isAdmin=([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if(-not $isAdmin){Start-Process powershell.exe -Verb RunAs -WindowStyle Hidden -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-STA','-WindowStyle','Hidden','-File',('"{0}"' -f $PSCommandPath),'-InstallPath',('"{0}"' -f $InstallPath));exit}
. (Join-Path $root 'Install-Whisper.ps1') -NoUi -InstallPath $InstallPath
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
[System.Windows.Forms.Application]::EnableVisualStyles()
Import-Module (Join-Path $root 'Whisper.Ui.psm1') -Force
$Theme=Get-FrivoTheme
$existing=Get-ExistingWhisperInstall $InstallPath
if($existing.State -eq 'None'){
  $legacyPath=Join-Path $env:ProgramFiles 'Whisper'
  $legacy=Get-ExistingWhisperInstall $legacyPath
  if($legacy.State -ne 'None'){$InstallPath=$legacy.Path;$existing=$legacy}
}
$form=New-FrivoForm -Theme $Theme -Title 'Evora Setup' -Width 620 -Height 500 -IconPath (Join-Path $root 'Evora.ico') -AppId 'Evora.Setup'
$header=New-FrivoHeader -Theme $Theme -Form $form -Title 'Welcome to Evora Setup' -Subtitle 'Private, local transcription for Frivo' -LogoPngPath (Join-Path $root 'Evora.png')
$body=New-Object System.Windows.Forms.Panel;$body.Location=[Drawing.Point]::new(0,76);$body.Size=[Drawing.Size]::new(620,362);$body.BackColor=$Theme.Bg;$form.Controls.Add($body)
$footer=New-Object System.Windows.Forms.Panel;$footer.Location=[Drawing.Point]::new(0,438);$footer.Size=[Drawing.Size]::new(620,62);$footer.BackColor=$Theme.Bg;$form.Controls.Add($footer)
$back=New-FrivoButton -Theme $Theme -Parent $footer -Text 'Back' -X 272 -Y 14 -W 96 -H 36
$next=New-FrivoButton -Theme $Theme -Parent $footer -Text 'Next' -X 380 -Y 14 -W 110 -H 36 -Primary $true
$cancel=New-FrivoButton -Theme $Theme -Parent $footer -Text 'Cancel' -X 502 -Y 14 -W 96 -H 36
function Page{$p=New-Object System.Windows.Forms.Panel;$p.Location=[Drawing.Point]::new(0,0);$p.Size=[Drawing.Size]::new(620,362);$p.BackColor=$Theme.Bg;$p.Visible=$false;$body.Controls.Add($p);return $p}
$old=Page;$oldText=New-FrivoLabel -Theme $Theme -Parent $old -Text '' -X 28 -Y 10 -W 564 -H 88 -Font $Theme.FontUI -Color $Theme.Ink;$oldCard=New-FrivoCard -Theme $Theme -Parent $old -X 24 -Y 104 -W 572 -H 136;$repair=New-FrivoRadio -Theme $Theme -Parent $oldCard -Text 'Repair or reinstall' -X 18 -Y 14 -W 536 -Checked $true;$repairNote=New-FrivoLabel -Theme $Theme -Parent $oldCard -Text 'Rebuilds the Python environment and service. Downloaded models are kept.' -X 38 -Y 36 -W 516 -H 30 -Font $Theme.FontSmall -Color $Theme.Dim;$remove=New-FrivoRadio -Theme $Theme -Parent $oldCard -Text 'Uninstall Evora' -X 18 -Y 74 -W 536;$removeNote=New-FrivoLabel -Theme $Theme -Parent $oldCard -Text 'Removes Evora, downloaded models, and the background service.' -X 38 -Y 96 -W 516 -H 30 -Font $Theme.FontSmall -Color $Theme.Dim
$welcome=Page;[void](New-FrivoLabel -Theme $Theme -Parent $welcome -Text 'This wizard will install Evora on your computer.' -X 28 -Y 12 -W 564 -H 22 -Font $Theme.FontMid -Color $Theme.Ink);[void](New-FrivoLabel -Theme $Theme -Parent $welcome -Text "Evora gives Frivo a private, local transcription service. Your audio is processed on this computer.`r`n`r`nIt installs its own stable Python environment and starts automatically with Windows. The first startup downloads the speech model.`r`n`r`nClick Next to continue." -X 28 -Y 44 -W 564 -H 180 -Font $Theme.FontUI -Color $Theme.Dim)
$location=Page;[void](New-FrivoLabel -Theme $Theme -Parent $location -Text 'DESTINATION FOLDER' -X 30 -Y 10 -W 400 -H 14 -Font $Theme.FontCaps -Color $Theme.Faint);$locCard=New-FrivoCard -Theme $Theme -Parent $location -X 24 -Y 30 -W 572 -H 58;$pathBox=New-FrivoTextBox -Theme $Theme -Parent $locCard -X 16 -Y 16 -W 428 -H 26;$pathBox.Text=$InstallPath;$browse=New-FrivoButton -Theme $Theme -Parent $locCard -Text 'Browse...' -X 456 -Y 12 -W 100 -H 32;$browse.Add_Click({$d=New-Object System.Windows.Forms.FolderBrowserDialog;if($d.ShowDialog() -eq 'OK'){$pathBox.Text=Join-Path $d.SelectedPath 'Evora'}})
$options=Page;[void](New-FrivoLabel -Theme $Theme -Parent $options -Text 'SHORTCUTS' -X 30 -Y 8 -W 400 -H 14 -Font $Theme.FontCaps -Color $Theme.Faint);$shortcuts=New-FrivoCard -Theme $Theme -Parent $options -X 24 -Y 28 -W 572 -H 58;$desktopShortcut=New-FrivoCheck -Theme $Theme -Parent $shortcuts -Text 'Create a desktop shortcut' -X 18 -Y 16 -W 536 -Checked $true;[void](New-FrivoLabel -Theme $Theme -Parent $options -Text 'STARTUP' -X 30 -Y 100 -W 400 -H 14 -Font $Theme.FontCaps -Color $Theme.Faint);$startupCard=New-FrivoCard -Theme $Theme -Parent $options -X 24 -Y 120 -W 572 -H 74;$startWithWindows=New-FrivoCheck -Theme $Theme -Parent $startupCard -Text 'Start Evora automatically when Windows starts' -X 18 -Y 12 -W 536 -Checked $true;[void](New-FrivoLabel -Theme $Theme -Parent $startupCard -Text 'Runs privately in the background so transcription is ready for Frivo.' -X 38 -Y 38 -W 516 -H 20 -Font $Theme.FontSmall -Color $Theme.Dim);[void](New-FrivoLabel -Theme $Theme -Parent $options -Text 'NETWORK' -X 30 -Y 208 -W 400 -H 14 -Font $Theme.FontCaps -Color $Theme.Faint);$net=New-FrivoCard -Theme $Theme -Parent $options -X 24 -Y 228 -W 572 -H 72;$lan=New-FrivoCheck -Theme $Theme -Parent $net -Text 'Allow Frivo connections from other devices on this network' -X 18 -Y 12 -W 536 -Checked $true;[void](New-FrivoLabel -Theme $Theme -Parent $net -Text 'Adds a Private-network rule for port 9000.' -X 38 -Y 38 -W 516 -H 20 -Font $Theme.FontSmall -Color $Theme.Dim)
$installPage=Page;$bar=New-FrivoProgress -Theme $Theme -Parent $installPage -X 24 -Y 14 -W 572 -H 10;$activity=New-FrivoLabel -Theme $Theme -Parent $installPage -Text 'Working' -X 24 -Y 28 -W 572 -H 18 -Font $Theme.FontSmall -Color $Theme.Dim;$log=New-FrivoTextBox -Theme $Theme -Parent $installPage -X 24 -Y 52 -W 572 -H 286 -Multiline
$done=Page;[void](New-FrivoLabel -Theme $Theme -Parent $done -Text 'Evora is installed.' -X 28 -Y 12 -W 564 -H 22 -Font $Theme.FontMid -Color $Theme.Ink);[void](New-FrivoLabel -Theme $Theme -Parent $done -Text 'Use the Evora desktop shortcut to see whether the service is running. In Frivo, select Evora under Settings > Providers and use http://localhost:9000.' -X 28 -Y 52 -W 564 -H 70 -Font $Theme.FontUI -Color $Theme.Dim);$launchCard=New-FrivoCard -Theme $Theme -Parent $done -X 24 -Y 144 -W 572 -H 62;$launchAfterInstall=New-FrivoCheck -Theme $Theme -Parent $launchCard -Text 'Launch Evora after setup finishes' -X 18 -Y 19 -W 536 -Checked $true
$pages=New-Object System.Collections.ArrayList;if($existing.State -ne 'None'){[void]$pages.Add(@{p=$old;t='Existing Evora installation';s='Repair, reinstall, or remove Evora';n='Next'})};[void]$pages.Add(@{p=$welcome;t='Welcome to Evora Setup';s='Private, local transcription for Frivo';n='Next'});[void]$pages.Add(@{p=$location;t='Select destination';s='Choose where to install the application';n='Next'});[void]$pages.Add(@{p=$options;t='Configuration';s='Startup and network access';n='Install'});[void]$pages.Add(@{p=$installPage;t='Installing';s='This can take several minutes';n='Next'});[void]$pages.Add(@{p=$done;t='Setup complete';s='Ready to connect with Frivo';n='Finish'})
$installIndex=$pages.Count-2;$doneIndex=$pages.Count-1;$script:i=0;if($existing.State -ne 'None'){$oldText.Text="Evora is already installed at:`r`n$($existing.Path)`r`n`r`nSelect an option to continue."}
function Show([int]$n){foreach($x in $pages){$x.p.Visible=$false};$pages[$n].p.Visible=$true;$header.Title.Text=$pages[$n].t;$header.Subtitle.Text=$pages[$n].s;$next.Text=$pages[$n].n;$back.Visible=($n -gt 0 -and $n -lt $installIndex);$back.Enabled=$back.Visible;$cancel.Enabled=($n -lt $installIndex);$next.Enabled=($n -ne $installIndex)}
$script:isInstalling=$false;$script:pulse=0;$pulseTimer=New-Object System.Windows.Forms.Timer;$pulseTimer.Interval=450;$pulseTimer.Add_Tick({if($script:isInstalling){$script:pulse=($script:pulse+1)%4;$activity.Text=('Working'+('.' * $script:pulse))}})
function Log([string]$m){$log.AppendText($m+"`r`n");$log.SelectionStart=$log.TextLength;$log.ScrollToCaret();[System.Windows.Forms.Application]::DoEvents()}
$back.Add_Click({if($script:i -gt 0){$script:i--;Show $script:i}});$cancel.Add_Click({$form.Close()});$next.Add_Click({$cur=$pages[$script:i];if($cur.p -eq $old -and $remove.Checked){Uninstall-Whisper $existing.Path;$form.Close();return};if($cur.p -eq $options){$script:i=$installIndex;Show $script:i;$script:isInstalling=$true;$pulseTimer.Start();Set-WhisperSetupPulse { [System.Windows.Forms.Application]::DoEvents() };try{Log 'Starting setup. Do not close this window. Installing packages can take several minutes.';Install-Whisper -Target $pathBox.Text -Repair:($existing.State -ne 'None' -and $repair.Checked) -AllowLan $lan.Checked -CreateDesktopShortcut $desktopShortcut.Checked -StartWithWindows $startWithWindows.Checked -OnProgress {param($p,$m)$bar.SetValue($p);Log $m};$script:isInstalling=$false;$pulseTimer.Stop();$script:i=$doneIndex;Show $script:i}catch{$script:isInstalling=$false;$pulseTimer.Stop();Log ('Setup failed: '+$_.Exception.Message);$next.Enabled=$true;$next.Text='Close';$cancel.Visible=$false};return};if($cur.p -eq $done){if($launchAfterInstall.Checked -and (Test-Path (Join-Path $pathBox.Text 'Whisper-Launcher.vbs'))){Start-Process (Join-Path $pathBox.Text 'Whisper-Launcher.vbs')};$form.Close();return};$script:i++;Show $script:i})
Show 0;[void]$form.ShowDialog()
